// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.Models;

#nullable disable

namespace WebApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("WebApp.Models.Services.ContactEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateOnly(2000, 10, 10),
                            Category = 0,
                            Created = new DateTime(2024, 11, 5, 18, 7, 41, 857, DateTimeKind.Local).AddTicks(9056),
                            Email = "adad@gmail.com",
                            FirstName = "Adam",
                            LastName = "Kowalski",
                            PhoneNumber = "123456234"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateOnly(2000, 10, 10),
                            Category = 0,
                            Created = new DateTime(2024, 11, 5, 18, 7, 41, 857, DateTimeKind.Local).AddTicks(9106),
                            Email = "robert@gmail.com",
                            FirstName = "Robert",
                            LastName = "Kowal",
                            PhoneNumber = "123742684"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateOnly(2000, 10, 10),
                            Category = 0,
                            Created = new DateTime(2024, 11, 5, 18, 7, 41, 857, DateTimeKind.Local).AddTicks(9109),
                            Email = "robert@gmail.com",
                            FirstName = "Robert",
                            LastName = "Kowal",
                            PhoneNumber = "124963748"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
